import re
from groq import Groq

def clean_generated_text(text):
    """
    Cleans and formats the text generated by the LLM.
    
    Args:
        text (str): The raw text generated by the LLM
        
    Returns:
        str: Cleaned and formatted text
    """
    # Remove HTML tags
    text = re.sub(r"<.*?>", "", text)
    
    # Remove special tokens
    text = re.sub(r"(Context:|Question:|Answer:)", "", text)
    
    # Clean up extra whitespace
    text = re.sub(r"\s+", " ", text).strip()
    
    return text

def generate_response_with_llm(context, question, api_key, model="llama-3.3-70b-versatile"):
    """
    Generates a response using the LLM API.
    
    Args:
        context (str): The context information for the question
        question (str): The question to answer
        api_key (str): The API key for the LLM service
        model (str): The model to use (defaults to llama-3.3-70b-versatile)
        
    Returns:
        str: The generated response
    """
    try:
        client = Groq(api_key=api_key)
        
        # Check if it's a medical term question
        is_medical_term = "in medical terms" in question.lower() or "what is" in question.lower()
        
        # Create a comprehensive prompt
        if is_medical_term:
            prompt = f"""
            You are a healthcare assistant providing accurate medical information to users.
            
            Context information: {context}
            
            Question: {question}
            
            Please answer in simple, easy-to-understand language that a non-medical person can comprehend.
            Focus on providing factual, accurate information from the context.
            
            Your response should be well-structured and cover the following aspects:
            1. What is this condition/term? (Provide a clear, simple explanation)
            2. What causes it? (List the main causes and risk factors)
            3. What are the symptoms? (Describe common signs and symptoms)
            4. How is it treated? (Explain standard treatments and management approaches)
            
            Use formatting like bullet points or numbered lists to organize the information when appropriate.
            Avoid medical jargon, or if you must use medical terms, explain them immediately.
            If specific information isn't available in the context, simply mention that rather than making up information.
            
            Answer:
            """
        else:
            prompt = f"""
            You are a healthcare assistant providing accurate medical information to users.
            
            Context information: {context}
            
            Question: {question}
            
            Please answer in simple, easy-to-understand language that a non-medical person can comprehend.
            Focus on providing factual, accurate information from the context.
            
            Your response should be well-structured and cover the following aspects:
            1. What is this drug used for? (Primary and other uses)
            2. What are the side effects? (Common and serious side effects)
            3. What precautions should be taken? (Important warnings, who shouldn't take it, interactions)
            4. How is it typically taken? (Dosage forms, administration information if available)
            
            Use formatting like bullet points or numbered lists to organize the information when appropriate.
            Avoid medical jargon, or if you must use medical terms, explain them immediately.
            If specific information isn't available in the context, simply mention that rather than making up information.
            
            Answer:
            """
        
        # Make the API call
        completion = client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.7,  # A bit of randomness but not too much
            max_tokens=800,   # Allow for detailed responses
            top_p=0.9,
        )
        
        # Get the generated text
        generated_text = completion.choices[0].message.content
        
        # Clean and return the text
        return clean_generated_text(generated_text)
        
    except Exception as e:
        error_message = f"Error generating response: {str(e)}"
        print(error_message)
        
        # If we're using the primary model, try falling back to the secondary model
        if model == "llama-3.3-70b-versatile":
            try:
                print("Falling back to mixtral-8x7b-32768 model")
                return generate_response_with_llm(context, question, api_key, "mixtral-8x7b-32768")
            except Exception as fallback_error:
                return f"Error with fallback model: {str(fallback_error)}"
        
        return error_message
