import re
from groq import Groq

def clean_generated_text(text):
    """
    Cleans and formats the text generated by the LLM.
    
    Args:
        text (str): The raw text generated by the LLM
        
    Returns:
        str: Cleaned and formatted text
    """
    # Remove HTML tags
    text = re.sub(r"<.*?>", "", text)
    
    # Remove special tokens
    text = re.sub(r"(Context:|Question:|Answer:)", "", text)
    
    # Clean up extra whitespace
    text = re.sub(r"\s+", " ", text).strip()
    
    return text

def generate_response_with_llm(context, question, api_key, model="llama-3.3-70b-versatile"):
    """
    Generates a response using the LLM API.
    
    Args:
        context (str): The context information for the question
        question (str): The question to answer
        api_key (str): The API key for the LLM service
        model (str): The model to use (defaults to llama-3.3-70b-versatile)
        
    Returns:
        str: The generated response
    """
    try:
        client = Groq(api_key=api_key)
        
        # Check if it's a medical term question
        is_medical_term = "in medical terms" in question.lower() or "what is" in question.lower()
        
        # Extract the drug name or medical term from the question for better formatting
        # This handles cases like "What are the uses, side effects, and precautions for the drug Aspirin?"
        if "drug" in question.lower():
            drug_name = question.lower().split("drug")[-1].strip("? ").strip()
        else:
            # Try to get the last word which is likely the drug/term name
            words = question.split()
            drug_name = words[-1].strip("?.,; ")
            
        # Capitalize the first letter of the drug name
        drug_name = drug_name.capitalize()
        
        # Create a comprehensive prompt
        if is_medical_term:
            prompt = f"""
            You are a healthcare assistant providing accurate medical information to users.
            
            Context information: {context}
            
            Question: {question}
            
            Please answer in simple, easy-to-understand language that a non-medical person can comprehend.
            Focus on providing factual, accurate information from the context.
            
            Your response MUST follow this EXACT four-section structure with these headings:
            
            # 1. What is {drug_name}?
            [Provide a clear, simple explanation of the medical term/condition in language a non-medical person can understand]
            
            # 2. What Causes {drug_name}?
            [List the main causes and risk factors using bullet points for clarity]
            
            # 3. What are the Symptoms of {drug_name}?
            [Describe common signs and symptoms using bullet points for clarity]
            
            # 4. How is {drug_name} Treated?
            [Explain standard treatments and management approaches using numbered points or bullets]
            
            Always maintain these exact section headings with the numbering. Use this structure for ALL medical term responses.
            Use bullet points within each section to organize the information clearly.
            Avoid medical jargon, or if you must use medical terms, explain them immediately.
            If specific information isn't available in the context, still include the section heading and mention that the information is not available rather than making up information.
            
            Answer:
            """
        else:
            prompt = f"""
            You are a healthcare assistant providing accurate medical information to users.
            
            Context information: {context}
            
            Question: {question}
            
            Please answer in simple, easy-to-understand language that a non-medical person can comprehend.
            Focus on providing factual, accurate information from the context.
            
            Your response MUST follow this EXACT four-section structure with these headings:
            
            # 1. Introduction to {drug_name} (also known as [alternative names])
            [Provide a brief introduction to the drug, including its alternative/brand names, what class of medication it is, and what forms it's available in (tablets, capsules, etc.)]
            
            # 2. Uses of {drug_name}
            [List the main purposes/conditions it treats, using bullet points for clarity]
            
            # 3. Side Effects of {drug_name}
            [First discuss common side effects, then clearly separate and discuss serious side effects that require medical attention. Use bullet points for clarity.]
            
            # 4. Precautions When Taking {drug_name}
            [List important warnings, who should avoid or use with caution, drug interactions, and special considerations for groups like pregnant women, elderly, etc.]
            
            Always maintain these exact section headings with the numbering. Use this structure for ALL drug information responses.
            Use bullet points within each section to organize the information clearly.
            Avoid medical jargon, or if you must use medical terms, explain them immediately.
            If specific information isn't available in the context, still include the section heading and mention that the information is not available rather than making up information.
            
            Answer:
            """
        
        # Make the API call
        completion = client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.7,  # A bit of randomness but not too much
            max_tokens=800,   # Allow for detailed responses
            top_p=0.9,
        )
        
        # Get the generated text
        generated_text = completion.choices[0].message.content
        
        # Clean and return the text
        return clean_generated_text(generated_text)
        
    except Exception as e:
        error_message = f"Error generating response: {str(e)}"
        print(error_message)
        
        # If we're using the primary model, try falling back to the secondary model
        if model == "llama-3.3-70b-versatile":
            try:
                print("Falling back to mixtral-8x7b-32768 model")
                return generate_response_with_llm(context, question, api_key, "mixtral-8x7b-32768")
            except Exception as fallback_error:
                return f"Error with fallback model: {str(fallback_error)}"
        
        return error_message
